### ISSUE TITLE
Add variable for setting backrefs

### ISSUE THREAD

**Issue by jason-riddle** [geerlingguy/ansible-role-raspberry-pi#4]
While inspecting [raspberry-pi-dramble/tasks/cgroup-features.yml (0af982d)](https://github.com/geerlingguy/raspberry-pi-dramble/blob/0af982d668a58a1ae13ef7390b0a9747f946514f/tasks/cgroup-features.yml), there's the following:

```yml
- name: Enable required cgroup features.
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
    state: present
```

This code block code be replaced by this role and with the following variable definition

```yml
raspberry_pi_boot_config_options:
  # Enable required cgroup features.
  - regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
    backrefs: True
```

However, the `backrefs: True` does not exist as an option today. Happy to contribute a PR to add this, but wanted to get some feedback on this change first.
